# Copyright (c) 2026 Valaris Studio
# SPDX-License-Identifier: AGPL-3.0-or-later

import enum
import itertools
import threading
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    BigInteger,
    Enum,
    ForeignKey,
    Identity,
    Index,
    String,
    event,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import JSON

from app.models.base import Base, UUIDMixin

if TYPE_CHECKING:
    from app.models.user import User


# Monotonic insertion-order key for the Board Timeline. `created_at` has 1s
# resolution and `id` is a random uuid4, so same-second bursts (one request, one
# runner tick) would otherwise sort randomly and corrupt the FE's forward fold.
#
# On Postgres `seq` is a real BIGINT IDENTITY (DB-assigned): the INSERT must OMIT
# the column so the identity fires. A python-side `default=` is the wrong tool —
# a callable returning None still makes SQLAlchemy BIND `seq = NULL`, and a
# `GENERATED BY DEFAULT` identity rejects an explicit NULL (NotNullViolation).
# So we attach NO column default and instead fill `seq` ONLY on SQLite (tests),
# via the before_insert hook below, since SQLite has no server-side autoincrement
# for a non-PK column. The counter is strictly increasing even within a single
# multi-row flush (a MAX(seq)+1 subquery would collapse to one value).
_seq_lock = threading.Lock()
_seq_counter = itertools.count(1)


class ActivityAction(str, enum.Enum):
    created = "created"
    updated = "updated"
    deleted = "deleted"
    moved = "moved"
    uploaded = "uploaded"
    archived = "archived"
    added_member = "added_member"
    removed_member = "removed_member"
    # DEP-4 (spec note 233e4429 §A7): card-dependency events.
    dependency_added = "dependency_added"
    dependency_removed = "dependency_removed"
    dependencies_replaced = "dependencies_replaced"
    # Loop templates (card 1ebeb37f). `published` is the operator intent a
    # flat `updated` would erase: a template's draft can move many times, but
    # only a publish changes what boards can bind. Migration 094 adds the
    # matching Postgres enum values.
    published = "published"
    unarchived = "unarchived"


class ActivityEntityType(str, enum.Enum):
    board = "board"
    column = "column"
    card = "card"
    note = "note"
    resource = "resource"
    definition = "definition"
    channel = "channel"
    git_repo = "git_repo"
    workspace = "workspace"
    member = "member"
    # Agent lifecycle (card 1ed41312): pause/resume/poll/deactivate/restart/
    # hard-delete. Migration 092 adds the matching Postgres enum value.
    agent = "agent"
    # Loop-template authoring (card 1ebeb37f). Bind/re-render/detach stay on
    # the `board` entity — they are things that happened TO A BOARD, and the
    # board timeline is where an operator looks for them. This entity covers
    # the template's own lifecycle: created, published, archived, restored.
    loop_template = "loop_template"
    # Skills Registry (spec note f58cae0c). Bind/unbind stay on the `board`
    # entity — they happened TO A BOARD. This entity covers the skill's own
    # lifecycle: created, updated, published, deleted. Migration 100 adds the
    # matching Postgres enum value.
    skill = "skill"


class Activity(Base, UUIDMixin):
    __tablename__ = "activities"
    __table_args__ = (
        Index("ix_activities_workspace_created", "workspace_id", "created_at"),
        Index("ix_activities_board_created", "board_id", "created_at"),
        Index("ix_activities_board_seq", "board_id", "seq"),
        Index("ix_activities_entity", "entity_type", "entity_id"),
        Index("ix_activities_actor", "actor_id"),
        Index("ix_activities_agent", "agent_id"),
    )

    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("workspaces.id", ondelete="CASCADE"), index=True
    )
    board_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("boards.id", ondelete="SET NULL"), nullable=True
    )
    actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id")
    )
    entity_type: Mapped[ActivityEntityType] = mapped_column(Enum(ActivityEntityType))
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True))
    action: Mapped[ActivityAction] = mapped_column(Enum(ActivityAction))
    summary: Mapped[str] = mapped_column(String(500), default="")
    # Additive localization contract. Legacy rows intentionally keep both NULL
    # and continue rendering `summary`; new system-authored writes provide a
    # stable semantic key plus data-only interpolation parameters.
    message_key: Mapped[str | None] = mapped_column(String(255), nullable=True)
    message_params: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    changes: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    # Board Timeline (contract v1): role-agnostic entity snapshot before/after
    # this event. NULL for pre-migration rows + events with no meaningful state.
    before_state: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    after_state: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    agent_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("agents.id", ondelete="SET NULL"), nullable=True
    )
    via_api_key: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    # Timeline insertion order. NO python default — see the module note above:
    # Postgres lets the IDENTITY assign it (INSERT omits the column); SQLite is
    # filled by `_fill_seq_on_sqlite` below.
    seq: Mapped[int] = mapped_column(BigInteger, Identity(always=False), nullable=False)

    actor: Mapped["User"] = relationship("User", foreign_keys=[actor_id], lazy="noload")

    @property
    def actor_name(self) -> str | None:
        return self.actor.name if self.actor else None

    @property
    def actor_email(self) -> str | None:
        return self.actor.email if self.actor else None


@event.listens_for(Activity, "before_insert")
def _fill_seq_on_sqlite(mapper, connection, target: "Activity") -> None:
    """Assign `seq` from a process-local counter on SQLite only. Postgres leaves
    `target.seq` None so the INSERT omits the column and the IDENTITY assigns it
    (binding an explicit NULL would violate the NOT NULL BY DEFAULT identity)."""
    if connection.dialect.name == "sqlite" and target.seq is None:
        with _seq_lock:
            target.seq = next(_seq_counter)
