# Copyright (c) 2026 Valaris Studio
# SPDX-License-Identifier: AGPL-3.0-or-later

"""The website toolset export (scripts/export-website-toolsets.py).

Guards the contract getbackplane.ai's `src/data/mcp-toolsets.ts` consumer
relies on: the five catalog groups in reading order, every hand tool naming a
catalog tool, the interactive hand being the server's default toolset, and
a header that tells the next editor how to regenerate instead of hand-editing.
"""

from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "export-website-toolsets.py"
SURFACE = (
    REPO_ROOT
    / "frontend/src/pages/documentation/mcp-reference/data/server-surface.json"
)

EXPECTED_GROUPS = [
    "startHere",
    "workManagement",
    "knowledgeContent",
    "collaboration",
    "autonomousOperations",
]


@pytest.fixture(scope="module")
def exporter():
    spec = importlib.util.spec_from_file_location("export_website_toolsets", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def export(exporter):
    return exporter.build_export(SURFACE)


def test_catalog_groups_in_reading_order(export):
    assert [group["group"] for group in export["catalog"]] == EXPECTED_GROUPS


def test_catalog_matches_server_surface_groups(export):
    surface = json.loads(SURFACE.read_text())
    by_id = {ts["id"]: ts["tools"] for ts in surface["toolsets"] if ts["kind"] == "group"}
    exported = {group["group"]: group["tools"] for group in export["catalog"]}
    assert exported["startHere"] == by_id["start-here"]
    assert exported["autonomousOperations"] == by_id["autonomous-operations"]
    assert sum(len(tools) for tools in exported.values()) == surface["tool_count"]


def test_hands_are_interactive_runner_stage_loop(export):
    assert [hand["id"] for hand in export["hands"]] == ["interactive", "runnerStage", "loop"]


def test_every_hand_tool_is_a_catalog_tool(export):
    catalog = {tool for group in export["catalog"] for tool in group["tools"]}
    for hand in export["hands"]:
        missing = [tool for tool in hand["tools"] if tool not in catalog]
        assert missing == [], f"{hand['id']} names tools outside the catalog: {missing}"
        assert len(set(hand["tools"])) == len(hand["tools"]), f"{hand['id']} repeats a tool"


def test_interactive_hand_is_the_default_toolset(export):
    surface = json.loads(SURFACE.read_text())
    interactive = next(hand for hand in export["hands"] if hand["id"] == "interactive")
    assert interactive["tools"] == surface["default_toolset"]["tools"]


def test_runner_stage_hand_is_the_reviewer_grant(export):
    from app.services.workspace_config import DEFAULT_PIPELINE_CONFIG

    reviewer = next(s for s in DEFAULT_PIPELINE_CONFIG["stages"] if s["role"] == "reviewer")
    granted = [name.removeprefix("mcp__valaris__") for name in reviewer["llm"]["tools"]]
    runner_stage = next(hand for hand in export["hands"] if hand["id"] == "runnerStage")
    assert runner_stage["tools"] == granted


def test_loop_hand_is_the_secretary_template_grant(export):
    from app.services.loop_templates import get_system_template

    secretary = get_system_template("secretary-loop")
    granted = [name.removeprefix("mcp__valaris__") for name in secretary.content.tools]
    loop = next(hand for hand in export["hands"] if hand["id"] == "loop")
    assert loop["tools"] == granted


def test_prompt_names_never_leak_into_hands(exporter, capsys):
    # decompose_card is an MCP prompt, not a tool; a grant that names it is
    # dropped with a warning rather than emitted into a hand.
    hand = exporter.intersect_with_catalog(
        "planner", ["mcp__valaris__get_card", "mcp__valaris__decompose_card"], {"get_card"}
    )
    assert hand == ["get_card"]
    assert "decompose_card" in capsys.readouterr().err


def test_generated_file_carries_regen_command_and_no_prompt_names(exporter, tmp_path):
    out = tmp_path / "mcp-toolsets.ts"
    exporter.main([str(out)])
    text = out.read_text()

    assert text.startswith("// GENERATED by internal repo scripts/export-website-toolsets.py")
    assert "regenerate with: " in text
    assert "python ../scripts/export-website-toolsets.py" in text
    # The build image runs the suite from a tarball without .git, where the
    # generator's documented fallback is "unknown" (cloudbuild 48baa77d).
    assert re.search(r"source commit (?:[0-9a-f]{7,40}|unknown)", text)
    assert "decompose_card" not in text

    for export_name in (
        "export type CatalogGroupId",
        "export type HandId",
        "export const MCP_CATALOG = [",
        "export type CatalogTool",
        "export const MCP_HANDS = [",
        "export type McpHand",
        "export const MCP_CATALOG_TOOLS",
        "export const MCP_CATALOG_SIZE",
        "export function handSize",
    ):
        assert export_name in text, f"missing export: {export_name}"
    assert "as const satisfies readonly { id: HandId; tools: readonly CatalogTool[] }[]" in text
