# Copyright (c) 2026 Valaris Studio
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Regression guard for the activities.seq Postgres NULL-bind outage (2026-06-08).

`activities.seq` is `GENERATED BY DEFAULT AS IDENTITY` on Postgres (migration
070). The model must let the IDENTITY assign it on Postgres — i.e. the compiled
INSERT must OMIT `seq` entirely. The original model attached a Python-side
`default=` callable that returned ``None`` on Postgres; SQLAlchemy then binds
``seq = NULL`` explicitly, and a BY-DEFAULT identity rejects an explicit NULL
(`NotNullViolationError`), 500-ing every activity insert — hence every card
mutation. The whole suite is SQLite, where the callable returned a real counter,
so this passed CI and only broke in prod.

These tests pin BOTH dialect behaviors without needing a live Postgres:
  - Postgres: the compiled INSERT must not name/bind `seq` (identity fills it).
  - SQLite: an inserted row must still receive a strictly-increasing `seq`.
"""

from __future__ import annotations

import uuid

import pytest
from sqlalchemy import insert
from sqlalchemy.dialects import postgresql

from app.models.activity import Activity, ActivityAction, ActivityEntityType


def _new_activity_kwargs(**overrides) -> dict:
    """The columns a service actually supplies — `seq` is deliberately absent,
    exactly like ActivityRepository.record(**kwargs)."""
    return dict(
        workspace_id=uuid.uuid4(),
        actor_id=uuid.uuid4(),
        entity_type=ActivityEntityType.card,
        entity_id=uuid.uuid4(),
        action=ActivityAction.updated,
        summary="touch",
    ) | overrides


def test_pg_insert_omits_seq_so_identity_assigns_it():
    """On Postgres the INSERT must NOT bind `seq` — the BY DEFAULT identity
    assigns it. If `seq` appears in the column list it is bound to NULL (no
    server value is computed at compile time for a python default returning
    None), which violates NOT NULL at execution time."""
    stmt = insert(Activity).values(**_new_activity_kwargs())
    compiled = stmt.compile(dialect=postgresql.dialect())

    bound_columns = set(compiled.compile_state._dict_parameters or {})
    assert "seq" not in bound_columns, (
        "Postgres INSERT binds `seq` (=> NULL) instead of letting the IDENTITY "
        f"assign it; bound columns were {sorted(bound_columns)}. "
        "A BY DEFAULT identity rejects an explicit NULL -> NotNullViolation."
    )
    assert "seq" not in str(compiled), "`seq` must not appear in the PG INSERT text"


@pytest.mark.asyncio
async def test_sqlite_insert_still_populates_seq(db_session, test_workspace, test_user):
    """SQLite (the test backend) has no server-side autoincrement for this
    non-PK column, so the model must still fill `seq` there — strictly
    increasing, even within a single flush of multiple rows."""
    real_parents = dict(workspace_id=test_workspace.id, actor_id=test_user.id)
    a = Activity(**_new_activity_kwargs(**real_parents))
    b = Activity(**_new_activity_kwargs(**real_parents))
    db_session.add_all([a, b])
    await db_session.flush()

    assert a.seq is not None and b.seq is not None, "seq must be populated on SQLite"
    assert a.seq != b.seq, "seq must be unique within a single flush"
