# Copyright (c) 2026 Valaris Studio
# SPDX-License-Identifier: AGPL-3.0-or-later

"""add monotonic seq insertion-order key to activities

Board Timeline ordering fix. `activities.created_at` has 1s resolution and `id`
is a random uuid4, so events created in the SAME tick (one API request, one
runner pipeline tick) sorted in a RANDOM order — corrupting the frontend forward
fold (a "remove participant" could land before its "add", a card "moved" before
its "created"). `seq` is a strictly-increasing BIGINT the timeline orders by.

Rolling-deploy safety (Cloud Run rolling update runs old + new code against the
new schema at once):
  1. Add `seq` NULLABLE first so in-flight OLD code inserting rows without `seq`
     does not violate a constraint mid-deploy.
  2. Backfill existing rows deterministically in (created_at, id) order via a
     window function — a stable best-effort reconstruction of historical order.
  3. Re-seed the identity sequence past MAX(seq), attach GENERATED BY DEFAULT AS
     IDENTITY, and set NOT NULL. GENERATED BY DEFAULT (not ALWAYS) means the DB
     auto-assigns `seq` for EVERY future insert with NO application change — so
     even residual old code finishing its rollout gets a valid `seq` for free.
  4. Add the (board_id, seq) ordering index the timeline query rides.

Postgres-only DDL (prod). Tests build the schema from the model via create_all,
where `seq` is a plain BIGINT filled by a dialect-guarded Python default.

Revision ID: 070
Revises: 069
Create Date: 2026-06-08
"""

from alembic import op
import sqlalchemy as sa

revision = "070"
down_revision = "069"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("activities", sa.Column("seq", sa.BigInteger(), nullable=True))

    # Deterministic backfill: oldest event gets the smallest seq.
    op.execute(
        """
        WITH ordered AS (
            SELECT id,
                   ROW_NUMBER() OVER (ORDER BY created_at ASC, id ASC) AS rn
            FROM activities
        )
        UPDATE activities a
        SET seq = ordered.rn
        FROM ordered
        WHERE a.id = ordered.id
        """
    )

    # Postgres requires NOT NULL before a column can become an identity.
    op.alter_column("activities", "seq", nullable=False)

    # Attach a GENERATED BY DEFAULT identity, then advance the sequence past the
    # backfilled max so newly inserted rows never collide with backfilled values.
    op.execute(
        "ALTER TABLE activities ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('activities', 'seq'),
            COALESCE((SELECT MAX(seq) FROM activities), 0) + 1,
            false
        )
        """
    )

    op.create_index("ix_activities_board_seq", "activities", ["board_id", "seq"])


def downgrade():
    op.drop_index("ix_activities_board_seq", table_name="activities")
    op.drop_column("activities", "seq")
