// Copyright (c) 2026 Valaris Studio
// SPDX-License-Identifier: MIT

package llm

import (
	"fmt"
	"strings"
	"unicode"
)

// Card 0ac035df — the Backplane deny-list speaks Claude's --disallowedTools
// vocabulary (`Bash(gh pr merge:*)`, `mcp__valaris__update_card`, `WebFetch`).
// Codex has no such flag; its shell policy is execpolicy: Starlark `.rules`
// files under $CODEX_HOME/rules/ with
//
//	prefix_rule(pattern=[...], decision="forbidden", justification="...")
//
// Non-obvious execpolicy facts (codex-cli 0.144.1, verified live 2026-09-02 by
// codex_execpolicy_live_integration_test.go):
//   - Matching is a LITERAL token prefix on the command codex is about to run,
//     after unwrapping exactly one `zsh -lc` layer — the same prefix semantics
//     (and the same nested-shell hole) as Claude's `Bash(cmd:*)`.
//   - Only `forbidden` is a hard floor: `prompt` auto-denies under
//     approval_policy="never" but is not a policy statement.
//   - $CODEX_HOME/rules/*.rules is honored on exec AND resume; a project-scope
//     `allow` cannot override a user-scope `forbidden`; `--ignore-rules` is the
//     only off switch and the driver never emits it.
//
// Translation buckets:
//   - `Bash(<cmd>)` / `Bash(<cmd>:*)` → one prefix_rule with the shell-split cmd
//   - `mcp__valaris__<tool>`          → subtracted from the MCP allowlist
//   - anything else                   → unenforceable on Codex; reported, never
//     silently dropped

// codexDenyRulesHeader is the first line of the generated rules file.
const codexDenyRulesHeader = "# Backplane shell deny-floor — generated by the runner on every launch; edits are discarded.\n"

const (
	bashDenyPrefix   = "Bash("
	mcpValarisPrefix = "mcp__valaris__"
)

// codexDenyTranslation is a deny-list split into what Codex can enforce and
// how. Input order is preserved within each bucket.
type codexDenyTranslation struct {
	PrefixRules [][]string // execpolicy prefix_rule patterns, one per enforceable Bash entry
	MCPDeny     []string   // full mcp__valaris__<tool> names to subtract from the MCP allowlist
	Unenforced  []string   // entries with no Codex equivalent (Claude built-ins, malformed Bash entries)
}

func translateCodexDeny(deny []string) codexDenyTranslation {
	var tr codexDenyTranslation
	for _, entry := range deny {
		entry = strings.TrimSpace(entry) // operator-authored JSON may carry stray whitespace/newlines
		if strings.HasPrefix(entry, mcpValarisPrefix) {
			tr.MCPDeny = append(tr.MCPDeny, entry)
			continue
		}
		if prefix, ok := codexBashPrefix(entry); ok {
			tr.PrefixRules = append(tr.PrefixRules, prefix)
			continue
		}
		tr.Unenforced = append(tr.Unenforced, entry)
	}
	return tr
}

// codexBashPrefix turns `Bash(<cmd>)` / `Bash(<cmd>:*)` into the literal token
// prefix execpolicy matches on. ok is false for a non-Bash entry, an unbalanced
// quote, or an empty command — an empty pattern would match EVERY command and
// brick the stage, so it is reported as unenforced instead.
func codexBashPrefix(entry string) (prefix []string, ok bool) {
	if !strings.HasPrefix(entry, bashDenyPrefix) || !strings.HasSuffix(entry, ")") {
		return nil, false
	}
	body := strings.TrimSuffix(strings.TrimPrefix(entry, bashDenyPrefix), ")")
	body = strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(body), ":*"))
	tokens, ok := shellSplit(body)
	if !ok || len(tokens) == 0 {
		return nil, false
	}
	return tokens, true
}

// shellSplit tokenizes a command the way a POSIX shell would before execution:
// whitespace separates tokens, single quotes are literal, double quotes allow
// `\"` and `\\`, and a backslash outside quotes escapes the next rune. ok is
// false on an unterminated quote or a trailing backslash.
func shellSplit(s string) (tokens []string, ok bool) {
	runes := []rune(s)
	var cur strings.Builder
	inToken := false
	var quote rune
	flush := func() {
		if inToken {
			tokens = append(tokens, cur.String())
			cur.Reset()
			inToken = false
		}
	}
	for i := 0; i < len(runes); i++ {
		r := runes[i]
		switch {
		case quote == '\'':
			if r == '\'' {
				quote = 0
			} else {
				cur.WriteRune(r)
			}
		case quote == '"':
			switch {
			case r == '"':
				quote = 0
			case r == '\\' && i+1 < len(runes) && (runes[i+1] == '"' || runes[i+1] == '\\'):
				i++
				cur.WriteRune(runes[i])
			default:
				cur.WriteRune(r)
			}
		case r == '\\':
			if i+1 >= len(runes) {
				return nil, false
			}
			i++
			cur.WriteRune(runes[i])
			inToken = true
		case r == '\'' || r == '"':
			quote = r
			inToken = true
		case unicode.IsSpace(r):
			flush()
		default:
			cur.WriteRune(r)
			inToken = true
		}
	}
	if quote != 0 {
		return nil, false
	}
	flush()
	return tokens, true
}

// renderCodexDenyRules renders the already-merged deny-list as an execpolicy
// rules file: the header, then one forbidden prefix_rule per Bash entry, with
// the original Backplane entry echoed as the justification so codex's
// rejection message names its source. Non-Bash entries are handled elsewhere
// (see translateCodexDeny) and produce no line. The exact bytes are pinned by
// codexFloorRulesGolden in codex_deny_rules_test.go.
func renderCodexDenyRules(deny []string) string {
	var b strings.Builder
	b.WriteString(codexDenyRulesHeader)
	for _, entry := range deny {
		entry = strings.TrimSpace(entry)
		prefix, ok := codexBashPrefix(entry)
		if !ok {
			continue
		}
		b.WriteString("prefix_rule(pattern=[")
		for i, token := range prefix {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(starlarkString(token))
		}
		fmt.Fprintf(&b, "], decision=\"forbidden\", justification=%s)\n", starlarkString("Backplane deny-floor: "+entry))
	}
	return b.String()
}

// starlarkString quotes s as a Starlark double-quoted string literal. Control
// runes are escaped, never emitted raw: the backend deny-list is
// operator-authored, and one raw newline inside a literal makes codex-cli
// 0.144.1 reject the WHOLE rules file ("unfinished string literal"), dropping
// the entire floor rather than one entry. The evaluator loads \n \r \t and
// \uXXXX escapes (verified 2026-09-02).
func starlarkString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\r':
			b.WriteString(`\r`)
		case r == '\t':
			b.WriteString(`\t`)
		case r < 0x20 || r == 0x7f:
			fmt.Fprintf(&b, `\u%04x`, r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// subtractTools returns allowed minus every name in denied, order preserved.
func subtractTools(allowed, denied []string) []string {
	if len(denied) == 0 {
		return allowed
	}
	drop := make(map[string]bool, len(denied))
	for _, d := range denied {
		drop[d] = true
	}
	kept := make([]string, 0, len(allowed))
	for _, tool := range allowed {
		if !drop[tool] {
			kept = append(kept, tool)
		}
	}
	return kept
}
