// Copyright (c) 2026 Valaris Studio
// SPDX-License-Identifier: MIT

package llm

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// Card 0ac035df — translating the Backplane deny-list (Claude --disallowedTools
// vocabulary) into Codex execpolicy `.rules`. Three buckets:
//   - `Bash(<cmd>:*)` / `Bash(<cmd>)` → prefix_rule(pattern=<shell-split cmd>, decision="forbidden")
//   - `mcp__valaris__<tool>`          → subtracted from the MCP allowlist (no rules equivalent)
//   - anything else (WebFetch, …)     → unenforceable on Codex; reported, never dropped silently
//
// Rendering pins EXACT bytes: the file is a security artifact and drift in
// quoting or ordering would only show up as a live escape.

// codexFloorRulesGolden is the byte-exact rules file for SafeToolDenyFloor.
// One header line, then one prefix_rule per floor entry in floor order, the
// original Backplane entry echoed as the justification so a rejection message
// (`rejected: Backplane deny-floor: Bash(gh pr merge:*)`) names its source.
const codexFloorRulesGolden = `# Backplane shell deny-floor — generated by the runner on every launch; edits are discarded.
prefix_rule(pattern=["gh", "pr", "merge"], decision="forbidden", justification="Backplane deny-floor: Bash(gh pr merge:*)")
prefix_rule(pattern=["gh", "pr", "review"], decision="forbidden", justification="Backplane deny-floor: Bash(gh pr review:*)")
prefix_rule(pattern=["gh", "pr", "close"], decision="forbidden", justification="Backplane deny-floor: Bash(gh pr close:*)")
prefix_rule(pattern=["git", "push", "--force"], decision="forbidden", justification="Backplane deny-floor: Bash(git push --force:*)")
prefix_rule(pattern=["git", "push", "--force-with-lease"], decision="forbidden", justification="Backplane deny-floor: Bash(git push --force-with-lease:*)")
prefix_rule(pattern=["git", "push", "origin", "main"], decision="forbidden", justification="Backplane deny-floor: Bash(git push origin main:*)")
prefix_rule(pattern=["git", "push", "origin", "master"], decision="forbidden", justification="Backplane deny-floor: Bash(git push origin master:*)")
prefix_rule(pattern=["git", "reset", "--hard"], decision="forbidden", justification="Backplane deny-floor: Bash(git reset --hard:*)")
`

func TestRenderCodexDenyRules_ExactFloorText(t *testing.T) {
	got := renderCodexDenyRules(SafeToolDenyFloor)
	if got != codexFloorRulesGolden {
		t.Errorf("rendered floor drifted from the golden bytes.\n got:\n%s\nwant:\n%s", got, codexFloorRulesGolden)
	}
	if countPrefixRules(got) != len(SafeToolDenyFloor) {
		t.Errorf("want %d prefix rules, got %d", len(SafeToolDenyFloor), countPrefixRules(got))
	}
}

func TestCodexDenyTranslation_BashPrefixSplitting(t *testing.T) {
	cases := []struct {
		entry string
		want  []string
	}{
		{"Bash(git push --force:*)", []string{"git", "push", "--force"}},
		{"Bash(gh pr merge)", []string{"gh", "pr", "merge"}}, // no :* suffix → same tokens
		{"Bash(gh pr merge:*)", []string{"gh", "pr", "merge"}},
		{`Bash(git commit -m "a b":*)`, []string{"git", "commit", "-m", "a b"}}, // shell-style quoting
		{`Bash(echo 'x y' z:*)`, []string{"echo", "x y", "z"}},
		{"Bash(  npm   publish  :*)", []string{"npm", "publish"}}, // whitespace-insensitive
	}
	for _, c := range cases {
		tr := translateCodexDeny([]string{c.entry})
		if len(tr.PrefixRules) != 1 || !reflect.DeepEqual(tr.PrefixRules[0], c.want) {
			t.Errorf("%s → PrefixRules %v, want [%v]", c.entry, tr.PrefixRules, c.want)
		}
		if len(tr.MCPDeny) != 0 || len(tr.Unenforced) != 0 {
			t.Errorf("%s must land only in PrefixRules, got mcp=%v unenforced=%v", c.entry, tr.MCPDeny, tr.Unenforced)
		}
	}
}

func TestCodexDenyTranslation_Buckets(t *testing.T) {
	tr := translateCodexDeny([]string{
		"Bash(gh pr merge:*)",
		"mcp__valaris__update_card",
		"WebFetch",
		"Bash(git reset --hard:*)",
		"mcp__valaris__move_card",
		"Edit(*.env)",
	})
	wantPrefix := [][]string{{"gh", "pr", "merge"}, {"git", "reset", "--hard"}}
	if !reflect.DeepEqual(tr.PrefixRules, wantPrefix) {
		t.Errorf("PrefixRules = %v, want %v (input order preserved)", tr.PrefixRules, wantPrefix)
	}
	wantMCP := []string{"mcp__valaris__update_card", "mcp__valaris__move_card"}
	if !reflect.DeepEqual(tr.MCPDeny, wantMCP) {
		t.Errorf("MCPDeny = %v, want %v", tr.MCPDeny, wantMCP)
	}
	wantUnenforced := []string{"WebFetch", "Edit(*.env)"}
	if !reflect.DeepEqual(tr.Unenforced, wantUnenforced) {
		t.Errorf("Unenforced = %v, want %v", tr.Unenforced, wantUnenforced)
	}
}

// A malformed Bash entry (empty command) cannot become an empty prefix rule —
// `pattern=[]` would match EVERY command and brick the stage. It is reported
// as unenforced instead.
func TestCodexDenyTranslation_EmptyBashEntryIsUnenforced(t *testing.T) {
	tr := translateCodexDeny([]string{"Bash()", "Bash(:*)", "Bash(   )"})
	if len(tr.PrefixRules) != 0 {
		t.Errorf("empty Bash entries must not produce prefix rules, got %v", tr.PrefixRules)
	}
	if len(tr.Unenforced) != 3 {
		t.Errorf("empty Bash entries must be reported as unenforced, got %v", tr.Unenforced)
	}
}

// A `"` inside an entry must render as a valid Starlark string (backslash
// escaped), both in the pattern token and in the echoed justification.
func TestRenderCodexDenyRules_EscapesQuotes(t *testing.T) {
	got := renderCodexDenyRules([]string{`Bash(echo "hi":*)`})
	wantLine := `prefix_rule(pattern=["echo", "hi"], decision="forbidden", justification="Backplane deny-floor: Bash(echo \"hi\":*)")`
	if !strings.Contains(got, wantLine) {
		t.Errorf("quote escaping wrong.\n got:\n%s\nwant line:\n%s", got, wantLine)
	}

	// A quote that survives shell-splitting (escaped in the entry) must be
	// escaped in the pattern token too.
	got = renderCodexDenyRules([]string{`Bash(say \"x\":*)`})
	if !strings.Contains(got, `pattern=["say", "\"x\""]`) {
		t.Errorf("pattern token with a literal quote must be Starlark-escaped, got:\n%s", got)
	}
	if strings.Contains(got, `""x""`) {
		t.Errorf("unescaped quote leaked into the pattern:\n%s", got)
	}
}

// Ground truth: the real codex evaluator must parse the rendered floor and
// agree on the decisions. Not integration-tagged — `codex execpolicy check`
// is a pure local evaluator (no model, no tokens); skipped without codex.
func TestCodexDenyRules_CheckCLIAgrees(t *testing.T) {
	if _, err := exec.LookPath("codex"); err != nil {
		t.Skip("no codex binary on PATH")
	}
	rulesPath := filepath.Join(t.TempDir(), "backplane-deny.rules")
	if err := os.WriteFile(rulesPath, []byte(renderCodexDenyRules(SafeToolDenyFloor)), 0o600); err != nil {
		t.Fatalf("write rules: %v", err)
	}

	check := func(tokens ...string) (decision string, matched int) {
		t.Helper()
		out, err := exec.Command("codex", append([]string{"execpolicy", "check", "--rules", rulesPath}, tokens...)...).Output()
		if err != nil {
			t.Fatalf("codex execpolicy check %v: %v (the rendered file must parse as Starlark)", tokens, err)
		}
		var verdict struct {
			MatchedRules []json.RawMessage `json:"matchedRules"`
			Decision     string            `json:"decision"`
		}
		if err := json.Unmarshal(out, &verdict); err != nil {
			t.Fatalf("unparseable check output %q: %v", out, err)
		}
		return verdict.Decision, len(verdict.MatchedRules)
	}

	if d, n := check("gh", "pr", "merge", "1"); d != "forbidden" || n == 0 {
		t.Errorf("gh pr merge 1 → decision %q (%d matches), want forbidden", d, n)
	}
	if d, n := check("git", "reset", "--hard", "HEAD~1"); d != "forbidden" || n == 0 {
		t.Errorf("git reset --hard → decision %q (%d matches), want forbidden", d, n)
	}
	if d, n := check("git", "status"); d != "" || n != 0 {
		t.Errorf("git status → decision %q (%d matches), want no match", d, n)
	}
	if d, n := check("git", "push", "origin", "feature/x"); d != "" || n != 0 {
		t.Errorf("git push origin feature/x → decision %q (%d matches), want no match (only main/master are floor-protected)", d, n)
	}
}

// ---------------------------------------------------------------------------
// Round 2 (adversarial review): control characters in a deny entry. The
// backend deny-list is operator-authored JSON, so a stray newline/tab/CR can
// reach the renderer. A raw control rune inside a Starlark string literal
// breaks the WHOLE rules file ("unfinished string literal" — verified against
// codex-cli 0.144.1), which would drop the entire floor, not just one entry.
// Design for the implementer: starlarkString escapes \n \r \t and every other
// control rune as \uXXXX (codex's evaluator loads \n, \t, \r, \u0001 and \x00
// escapes, verified 2026-09-02); the entry stays enforced, never dropped.
// ---------------------------------------------------------------------------

// controlCharDenyEntries are the review's adversarial inputs (rules/adv-newline,
// adv-cr, adv-tab, adv-nul, adv-newline_just) as Backplane deny entries.
var controlCharDenyEntries = []string{
	"Bash(gh pr merge\n:*)",
	"Bash(gh pr merge\r:*)",
	"Bash(echo\tx:*)",
	"Bash(gh pr\x00merge:*)",
	"Bash(gh pr merge:*)\n",
	"Bash(git push --force \x01\x1f:*)",
}

// starlarkLiteralsTerminated reports whether every `"…"` literal on the line
// closes (backslash-escaped quotes do not count as delimiters).
func starlarkLiteralsTerminated(line string) bool {
	inLiteral := false
	escaped := false
	for _, r := range line {
		switch {
		case escaped:
			escaped = false
		case r == '\\' && inLiteral:
			escaped = true
		case r == '"':
			inLiteral = !inLiteral
		}
	}
	return !inLiteral
}

func hasRawControlRune(line string) bool {
	for _, r := range line {
		if r < 0x20 || r == 0x7f {
			return true
		}
	}
	return false
}

func TestRenderCodexDenyRules_ControlCharactersNeverBreakTheFile(t *testing.T) {
	rendered := renderCodexDenyRules(append(append([]string{}, SafeToolDenyFloor...), controlCharDenyEntries...))

	// Hermetic half: one physical line per rule, no raw control runes anywhere
	// (they must have been escaped), every string literal terminated.
	if strings.Contains(rendered, "\r") {
		t.Errorf("rendered file must not contain a raw CR:\n%q", rendered)
	}
	lines := strings.Split(strings.TrimSuffix(rendered, "\n"), "\n")
	wantLines := 1 + len(SafeToolDenyFloor) + len(controlCharDenyEntries)
	if len(lines) != wantLines {
		t.Errorf("want %d physical lines (header + one per entry), got %d:\n%q", wantLines, len(lines), rendered)
	}
	for i, line := range lines {
		if hasRawControlRune(line) {
			t.Errorf("line %d carries a raw control rune (must be escaped as \\n/\\t/\\uXXXX): %q", i+1, line)
		}
		if !starlarkLiteralsTerminated(line) {
			t.Errorf("line %d has an unterminated Starlark string literal: %q", i+1, line)
		}
	}

	// Live half: the real evaluator must load the file and still forbid the
	// floor command; a load error means the whole floor is gone.
	if _, err := exec.LookPath("codex"); err != nil {
		t.Skip("no codex binary on PATH — hermetic half only")
	}
	rulesPath := filepath.Join(t.TempDir(), "backplane-deny.rules")
	if err := os.WriteFile(rulesPath, []byte(rendered), 0o600); err != nil {
		t.Fatalf("write rules: %v", err)
	}
	out, err := exec.Command("codex", "execpolicy", "check", "--rules", rulesPath, "gh", "pr", "merge", "1").CombinedOutput()
	if err != nil {
		t.Fatalf("codex refused to LOAD the rendered rules file (the whole floor would be dropped): %v\n%s", err, out)
	}
	if !strings.Contains(string(out), `"decision":"forbidden"`) {
		t.Errorf("gh pr merge 1 must still be forbidden with control-char entries present, got %s", out)
	}
}

// The escaped entry must remain a prefix rule — dropping it to Unenforced
// would be the easy but wrong fix.
func TestCodexDenyTranslation_ControlCharsStillEnforced(t *testing.T) {
	for _, entry := range controlCharDenyEntries {
		tr := translateCodexDeny([]string{entry})
		if len(tr.PrefixRules) != 1 {
			t.Errorf("%q must translate to exactly one prefix rule (escaped), got prefix=%v unenforced=%v", entry, tr.PrefixRules, tr.Unenforced)
		}
		if len(tr.Unenforced) != 0 {
			t.Errorf("%q must not be reported unenforced, got %v", entry, tr.Unenforced)
		}
	}
	// And the rendered rule for the newline entry still targets gh pr merge.
	rendered := renderCodexDenyRules([]string{"Bash(gh pr merge\n:*)"})
	if !strings.Contains(rendered, `prefix_rule(pattern=["gh", "pr", "merge"]`) {
		t.Errorf("newline-tainted entry must still render the gh pr merge prefix, got:\n%q", rendered)
	}
}
