#!/usr/bin/env python3
# Copyright (c) 2026 Valaris Studio
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Export the MCP catalog + three representative hands to getbackplane.ai.

The website's MCP section renders `src/data/mcp-toolsets.ts`: the full catalog
as one dot per tool, grouped, with the active hand's tools lit. This script
is the only writer of that file, so the site never carries a hand-authored
snapshot that drifts from the server.

Sources:
  * frontend/src/pages/documentation/mcp-reference/data/server-surface.json
    (plain JSON, written by mcp-server/scripts/export-tool-catalog.py) — the
    five group toolsets and the interactive default hand.
  * backend DEFAULT_PIPELINE_CONFIG — the reviewer stage's `llm.tools` grant.
  * backend loop template registry — the secretary loop's `content.tools`.

Run with the backend virtualenv active:

    cd backend && source .venv/bin/activate
    python ../scripts/export-website-toolsets.py <intern-website>/src/data/mcp-toolsets.ts
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "backend"))

DEFAULT_SURFACE = (
    REPO_ROOT / "frontend/src/pages/documentation/mcp-reference/data/server-surface.json"
)
REGEN_COMMAND = (
    "cd backend && source .venv/bin/activate && "
    "python ../scripts/export-website-toolsets.py <intern-website>/src/data/mcp-toolsets.ts"
)
MCP_PREFIX = "mcp__valaris__"

# Reading order of the website's catalog; surface id → TS CatalogGroupId.
GROUP_IDS = (
    ("start-here", "startHere"),
    ("work-management", "workManagement"),
    ("knowledge-content", "knowledgeContent"),
    ("collaboration", "collaboration"),
    ("autonomous-operations", "autonomousOperations"),
)
REVIEWER_STAGE_ROLE = "reviewer"
LOOP_TEMPLATE_SLUG = "secretary-loop"


def intersect_with_catalog(label: str, grant: list[str], catalog: set[str]) -> list[str]:
    """Strip the MCP prefix and keep only real tools, warning about the rest.

    A grant can name a prompt (`decompose_card`) or a tool this catalog no
    longer has; a hand that lights a dot the catalog lacks would be a lie.
    """
    kept: list[str] = []
    for full_name in grant:
        name = full_name.removeprefix(MCP_PREFIX)
        if name in catalog:
            kept.append(name)
        else:
            print(f"warning: {label} grant names {name!r}, not a catalog tool; dropped", file=sys.stderr)
    return kept


def build_export(surface_path: Path = DEFAULT_SURFACE) -> dict:
    from app.services.loop_templates import get_system_template
    from app.services.workspace_config import DEFAULT_PIPELINE_CONFIG

    surface = json.loads(surface_path.read_text())
    groups_by_id = {ts["id"]: ts["tools"] for ts in surface["toolsets"] if ts["kind"] == "group"}
    catalog = [{"group": ts_id, "tools": list(groups_by_id[surface_id])} for surface_id, ts_id in GROUP_IDS]
    catalog_tools = {tool for group in catalog for tool in group["tools"]}

    reviewer = next(s for s in DEFAULT_PIPELINE_CONFIG["stages"] if s["role"] == REVIEWER_STAGE_ROLE)
    loop_template = get_system_template(LOOP_TEMPLATE_SLUG)
    if loop_template is None:
        raise SystemExit(f"loop template {LOOP_TEMPLATE_SLUG!r} not in the registry")

    hands = [
        {"id": "interactive", "tools": intersect_with_catalog("default toolset", surface["default_toolset"]["tools"], catalog_tools)},
        {"id": "runnerStage", "tools": intersect_with_catalog(f"{REVIEWER_STAGE_ROLE} stage", reviewer["llm"]["tools"], catalog_tools)},
        {"id": "loop", "tools": intersect_with_catalog(LOOP_TEMPLATE_SLUG, list(loop_template.content.tools), catalog_tools)},
    ]
    return {"catalog": catalog, "hands": hands, "source_commit": source_commit()}


def source_commit() -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _ts_string_list(items: list[str], indent: str) -> str:
    return "".join(f'{indent}"{item}",\n' for item in items)


def render_ts(export: dict) -> str:
    group_ids = "".join(f'  | "{ts_id}"\n' for _, ts_id in GROUP_IDS)
    hand_ids = " | ".join(f'"{hand["id"]}"' for hand in export["hands"])
    catalog = "".join(
        f'  {{\n    group: "{group["group"]}",\n    tools: [\n{_ts_string_list(group["tools"], "      ")}    ],\n  }},\n'
        for group in export["catalog"]
    )
    hands = "".join(
        f'  {{\n    id: "{hand["id"]}",\n    tools: [\n{_ts_string_list(hand["tools"], "      ")}    ],\n  }},\n'
        for hand in export["hands"]
    )
    return f"""// GENERATED by internal repo scripts/export-website-toolsets.py from
// mcp-server's server-surface.json + backend defaults — do not edit;
// regenerate with: {REGEN_COMMAND}
// source commit {export["source_commit"]}

export type CatalogGroupId =
{group_ids.rstrip()};

export type HandId = {hand_ids};

export const MCP_CATALOG = [
{catalog}] as const satisfies readonly {{
  group: CatalogGroupId;
  tools: readonly string[];
}}[];

// Every hand tool must name a catalog tool; a typo fails type-checking.
export type CatalogTool = (typeof MCP_CATALOG)[number]["tools"][number];

// interactive = the server's default toolset; runnerStage = the default
// pipeline's reviewer stage grant; loop = the secretary loop template's grant.
export const MCP_HANDS = [
{hands}] as const satisfies readonly {{ id: HandId; tools: readonly CatalogTool[] }}[];

export type McpHand = (typeof MCP_HANDS)[number];

export const MCP_CATALOG_TOOLS: readonly CatalogTool[] = MCP_CATALOG.flatMap(
  (group) => group.tools,
);

export const MCP_CATALOG_SIZE = MCP_CATALOG_TOOLS.length;

export function handSize(hand: McpHand): number {{
  return hand.tools.length;
}}
"""


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("out", type=Path, help="path to intern-website/src/data/mcp-toolsets.ts")
    parser.add_argument("--surface", type=Path, default=DEFAULT_SURFACE)
    args = parser.parse_args(argv)

    export = build_export(args.surface)
    args.out.write_text(render_ts(export))
    sizes = ", ".join(f'{hand["id"]}={len(hand["tools"])}' for hand in export["hands"])
    catalog_size = sum(len(group["tools"]) for group in export["catalog"])
    print(f"{args.out}: catalog={catalog_size} hands: {sizes}")


if __name__ == "__main__":
    main()
