// Copyright (c) 2026 Valaris Studio
// SPDX-License-Identifier: AGPL-3.0-or-later

import type { DocumentationLocaleCopy } from "./types";

export const EN_DOCUMENTATION: DocumentationLocaleCopy = {
  locale: "en",
  version: "2026-08-25.1",
  shell: {
    eyebrow: "Platform",
    title: "Documentation",
    description: "A tour of Backplane for operators, teammates, and the curious.",
    tableOfContents: "Table of contents",
    tableOfContentsAriaLabel: "Documentation table of contents",
    sectionsAriaLabel: "Documentation sections",
    breadcrumbAriaLabel: "Breadcrumb",
    breadcrumbRoot: "Documentation",
    startHere: "Start here",
    notFoundBreadcrumb: "Not found",
    notFoundTitle: "We can't find that section",
    notFoundBody:
      "The URL references a section that is not in the table of contents. Return to the documentation landing page and choose a section from the list.",
    fallbackTitle: "English source shown",
    fallbackBody:
      "This section has not been translated into the selected language yet. Its English source is shown without changing commands, identifiers, routes, or code examples.",
    copyCode: "Copy code",
    copiedCode: "Copied",
    copiedToast: "Copied to clipboard",
    screenshotPlaceholder: "[SCREENSHOT]",
  },
  landing: {
    eyebrow: "Documentation",
    title: "Learn the platform, configure it for your team, and watch runners work.",
    description:
      "An operator-first tour of Backplane, from understanding runners to configuring custom roles. It is direct about what works and what is still rough.",
    featuredLabel: "Start here",
    featuredDescription:
      "A short essay on what the platform does, who it is for, and where to look next.",
  },
  mcpReference: {
    navAriaLabel: "MCP reference",
    searchAriaLabel: "Search MCP reference",
    searchPlaceholder: 'Search tools…  ("/" to focus)',
    filterAriaLabel: "Filter by kind",
    filterLabels: {
      all: "All",
      read: "Read",
      write: "Write",
      composite: "Composite",
    },
    noMatches: "No matches.",
    noMatchesFor: 'No matches for "{{query}}".',
    clearSearchAndFilters: "Clear search and filters",
    promptsGroup: "Prompts",
    resourcesGroup: "MCP Resources",
    noResultsDetail:
      "Nothing matches the current search and filters — clear them in the list pane to start over.",
    selectDetailBeforeShortcut:
      "Select a tool from the list to see its parameters, gotchas, and an example prompt — or press",
    selectDetailAfterShortcut: "to search.",
    copyToolId: "Copy tool id",
    parameters: "Parameters",
    gotchas: "Gotchas",
    dangerZone: "Danger zone",
    examplePrompt: "Example prompt",
    relatedTools: "Related tools",
    backToList: "Back to list",
    noParameters: "No parameters.",
    parameterName: "Name",
    parameterRequired: "Required",
    parameterDescription: "Description",
    requiredValue: "required",
    optionalValue: "optional",
    copyExamplePrompt: "Copy example prompt",
    annotationReadOnly: "Read-only",
    annotationDestructive: "Destructive",
    annotationIdempotent: "Idempotent",
    wireDescriptionTitle: "What the model sees",
    inDefaultHand: "In default hand",
  },
  groupTitles: {
    introduction: "Introduction",
    "core-concepts": "Core Concepts",
    installing: "Installing Backplane",
    "getting-started": "Getting Started",
    configuration: "Configuration",
    operating: "Operating the Platform",
    "under-the-hood": "Under the Hood",
    extending: "Extending Backplane",
    reference: "Reference",
    "honest-remarks": "Honest Remarks",
  },
  sectionTitles: {
    "what-backplane-is": "What Backplane Is",
    "what-it-is-not": "What It Is NOT",
    "quick-tour": "Quick Tour (5-minute read)",
    "workspaces-boards-columns-cards": "Workspaces, Boards, Columns, Cards",
    runners: "Runners (the credentialed process)",
    "agent-teams": "Agent Teams",
    "roles-and-pipelines": "Roles and Pipelines",
    prompts: "Prompts",
    approvals: "Approvals",
    "loop-mode": "Loop Mode",
    skills: "Skills (versioned procedural knowledge)",
    "install-with-docker-compose": "Install with Docker Compose",
    "securing-a-self-hosted-deployment": "Securing a Self-Hosted Deployment",
    "upgrading-backplane": "Upgrading Backplane",
    "backup-and-restore": "Backup and Restore",
    "creating-your-first-workspace": "Creating Your First Workspace",
    "your-first-board-and-card": "Your First Board and Card",
    "installing-the-mcp-server": "Installing the MCP Server in Your Agent Client",
    "registering-a-runner": "Registering a Runner",
    "your-first-pipeline-run": "Your First Pipeline Run (Guided Walkthrough)",
    "troubleshooting-your-first-run": "Troubleshooting Your First Run",
    "pipeline-builder": "Pipeline Builder — Every Field Explained",
    "prompt-authoring-guide": "Prompt Authoring Guide",
    "custom-roles": "Custom Roles (the real payoff)",
    sensors: "Sensors",
    "approval-categories-and-risk-scoring": "Approval Categories and Risk Scoring",
    "budget-and-cost-controls": "Budget and Cost Controls",
    "git-configuration-and-review-modes": "Git Configuration and Review Modes",
    "reading-the-runner-overview": "Reading the Runner Overview",
    "debugging-a-stuck-card": "Debugging a Stuck Card",
    "the-observer-panel": "The Observer Panel",
    "activity-history-and-audit-logs": "Activity History and Audit Logs",
    "webhooks-and-external-notifications": "Webhooks and External Notifications",
    "rollback-and-recovery-playbook": "Rollback and Recovery Playbook",
    "architecture-overview": "Architecture Overview (the four surfaces)",
    "event-bus-and-websocket-model": "The Event Bus and WebSocket Model",
    "fractional-indexing": "Fractional Indexing",
    idempotency: "Idempotency and Why It Matters",
    "platform-authority-principle": "Platform Authority Principle",
    "model-agnostic-roles": "Model-Agnostic Roles (future-facing)",
    "adding-a-new-mcp-tool": "Adding a New MCP Tool",
    "adding-a-new-pipeline-stage-variant": "Adding a New Pipeline Stage Variant",
    "integrating-a-new-git-host": "Integrating a New Git Host",
    "writing-a-custom-sensor": "Writing a Custom Sensor",
    "mcp-tool-catalog": "MCP Tool Catalog",
    "mcp-toolsets": "MCP Toolsets",
    "mcp-prompt-catalog": "MCP Prompt Catalog",
    "event-taxonomy": "Event Taxonomy",
    "column-type-semantics": "Column Type Semantics",
    "card-type-and-priority": "Card Type and Priority",
    "api-authentication-modes": "API Authentication Modes",
    "environment-variables": "Environment Variables",
    "what-works-well": "What Works Well",
    "known-rough-edges": "Known Rough Edges",
    "actively-working-on": "What We're Actively Working On",
    "the-north-star": "The North Star",
  },
};
