// Copyright (c) 2026 Valaris Studio
// SPDX-License-Identifier: AGPL-3.0-or-later

import type { DocumentationLocaleCopy } from "./types";

export const ES_DOCUMENTATION: DocumentationLocaleCopy = {
  locale: "es",
  version: "2026-08-25.1",
  shell: {
    eyebrow: "Plataforma",
    title: "Documentación",
    description: "Un recorrido por Backplane para operadores, equipos y personas curiosas.",
    tableOfContents: "Tabla de contenidos",
    tableOfContentsAriaLabel: "Tabla de contenidos de la documentación",
    sectionsAriaLabel: "Secciones de documentación",
    breadcrumbAriaLabel: "Ruta de navegación",
    breadcrumbRoot: "Documentación",
    startHere: "Comienza aquí",
    notFoundBreadcrumb: "No encontrada",
    notFoundTitle: "No encontramos esa sección",
    notFoundBody:
      "La URL hace referencia a una sección que no está en la tabla de contenidos. Vuelve al inicio de la documentación y elige una sección de la lista.",
    fallbackTitle: "Se muestra la fuente en inglés",
    fallbackBody:
      "Esta sección todavía no se ha traducido al idioma seleccionado. Mostramos su fuente en inglés sin alterar comandos, identificadores, rutas ni ejemplos de código.",
    copyCode: "Copiar código",
    copiedCode: "Copiado",
    copiedToast: "Copiado al portapapeles",
    screenshotPlaceholder: "[CAPTURA DE PANTALLA]",
  },
  landing: {
    eyebrow: "Documentación",
    title: "Aprende la plataforma, configúrala para tu equipo y observa cómo trabajan los runners.",
    description:
      "Un recorrido por Backplane pensado para operadores, desde entender los runners hasta configurar roles personalizados. Explica directamente qué funciona y qué todavía necesita trabajo.",
    featuredLabel: "Comienza aquí",
    featuredDescription:
      "Una explicación breve de qué hace la plataforma, para quién está diseñada y dónde continuar.",
  },
  mcpReference: {
    navAriaLabel: "Referencia MCP",
    searchAriaLabel: "Buscar en la referencia MCP",
    searchPlaceholder: 'Buscar herramientas…  ("/" para enfocar)',
    filterAriaLabel: "Filtrar por tipo",
    filterLabels: {
      all: "Todos",
      read: "Lectura",
      write: "Escritura",
      composite: "Compuesto",
    },
    noMatches: "No hay coincidencias.",
    noMatchesFor: 'No hay coincidencias para "{{query}}".',
    clearSearchAndFilters: "Limpiar búsqueda y filtros",
    promptsGroup: "Prompts",
    resourcesGroup: "Recursos MCP",
    noResultsDetail:
      "No hay resultados para la búsqueda y los filtros actuales. Límpialos en el panel de la lista para comenzar de nuevo.",
    selectDetailBeforeShortcut:
      "Selecciona una herramienta de la lista para ver sus parámetros, advertencias y un prompt de ejemplo, o presiona",
    selectDetailAfterShortcut: "para buscar.",
    copyToolId: "Copiar identificador de la herramienta",
    parameters: "Parámetros",
    gotchas: "Advertencias",
    dangerZone: "Zona de peligro",
    examplePrompt: "Prompt de ejemplo",
    relatedTools: "Herramientas relacionadas",
    backToList: "Volver a la lista",
    noParameters: "Sin parámetros.",
    parameterName: "Nombre",
    parameterRequired: "Obligatorio",
    parameterDescription: "Descripción",
    requiredValue: "obligatorio",
    optionalValue: "opcional",
    copyExamplePrompt: "Copiar prompt de ejemplo",
    annotationReadOnly: "Solo lectura",
    annotationDestructive: "Destructiva",
    annotationIdempotent: "Idempotente",
    wireDescriptionTitle: "Lo que ve el modelo",
    inDefaultHand: "En la mano predeterminada",
  },
  groupTitles: {
    introduction: "Introducción",
    "core-concepts": "Conceptos principales",
    installing: "Instalación de Backplane",
    "getting-started": "Primeros pasos",
    configuration: "Configuración",
    operating: "Operación de la plataforma",
    "under-the-hood": "Bajo el capó",
    extending: "Extensión de Backplane",
    reference: "Referencia",
    "honest-remarks": "Observaciones honestas",
  },
  sectionTitles: {
    "what-backplane-is": "Qué es Backplane",
    "what-it-is-not": "Qué NO es",
    "quick-tour": "Recorrido rápido (5 minutos)",
    "workspaces-boards-columns-cards": "Espacios de trabajo, tableros, columnas y tarjetas",
    runners: "Runners (el proceso con credenciales)",
    "agent-teams": "Equipos de agentes",
    "roles-and-pipelines": "Roles y pipelines",
    prompts: "Prompts",
    approvals: "Aprobaciones",
    "loop-mode": "Modo bucle",
    skills: "Habilidades (conocimiento procedimental versionado)",
    "install-with-docker-compose": "Instalación con Docker Compose",
    "securing-a-self-hosted-deployment": "Protección de un despliegue autohospedado",
    "upgrading-backplane": "Actualización de Backplane",
    "backup-and-restore": "Respaldo y restauración",
    "creating-your-first-workspace": "Creación de tu primer espacio de trabajo",
    "your-first-board-and-card": "Tu primer tablero y tu primera tarjeta",
    "installing-the-mcp-server": "Instalación del servidor MCP en tu cliente de agentes",
    "registering-a-runner": "Registro de un Runner",
    "your-first-pipeline-run": "Tu primera ejecución del pipeline (recorrido guiado)",
    "troubleshooting-your-first-run": "Solución de problemas de tu primera ejecución",
    "pipeline-builder": "Constructor de pipelines: explicación de cada campo",
    "prompt-authoring-guide": "Guía para escribir prompts",
    "custom-roles": "Roles personalizados (el beneficio real)",
    sensors: "Sensores",
    "approval-categories-and-risk-scoring": "Categorías de aprobación y puntuación de riesgo",
    "budget-and-cost-controls": "Controles de presupuesto y costos",
    "git-configuration-and-review-modes": "Configuración de Git y modos de revisión",
    "reading-the-runner-overview": "Lectura del resumen de Runners",
    "debugging-a-stuck-card": "Diagnóstico de una tarjeta bloqueada",
    "the-observer-panel": "El panel del observador",
    "activity-history-and-audit-logs": "Historial de actividad y registros de auditoría",
    "webhooks-and-external-notifications": "Webhooks y notificaciones externas",
    "rollback-and-recovery-playbook": "Guía de reversión y recuperación",
    "architecture-overview": "Resumen de arquitectura (las cuatro superficies)",
    "event-bus-and-websocket-model": "El bus de eventos y el modelo WebSocket",
    "fractional-indexing": "Indexación fraccionaria",
    idempotency: "Idempotencia y por qué importa",
    "platform-authority-principle": "Principio de autoridad de la plataforma",
    "model-agnostic-roles": "Roles independientes del modelo (visión futura)",
    "adding-a-new-mcp-tool": "Cómo agregar una nueva herramienta MCP",
    "adding-a-new-pipeline-stage-variant": "Cómo agregar una variante de etapa del pipeline",
    "integrating-a-new-git-host": "Integración de un nuevo proveedor Git",
    "writing-a-custom-sensor": "Cómo escribir un sensor personalizado",
    "mcp-tool-catalog": "Catálogo de herramientas MCP",
    "mcp-toolsets": "Toolsets MCP",
    "mcp-prompt-catalog": "Catálogo de prompts MCP",
    "event-taxonomy": "Taxonomía de eventos",
    "column-type-semantics": "Semántica de los tipos de columna",
    "card-type-and-priority": "Tipo y prioridad de las tarjetas",
    "api-authentication-modes": "Modos de autenticación de la API",
    "environment-variables": "Variables de entorno",
    "what-works-well": "Qué funciona bien",
    "known-rough-edges": "Aspectos problemáticos conocidos",
    "actively-working-on": "En qué estamos trabajando activamente",
    "the-north-star": "La estrella polar",
  },
};
