// Copyright (c) 2026 Valaris Studio
// SPDX-License-Identifier: AGPL-3.0-or-later

import type { DocumentationLocaleCopy } from "./types";

export const PT_BR_DOCUMENTATION: DocumentationLocaleCopy = {
  locale: "pt-BR",
  version: "2026-08-25.1",
  shell: {
    eyebrow: "Plataforma",
    title: "Documentação",
    description: "Um guia do Backplane para operadores, equipes e pessoas curiosas.",
    tableOfContents: "Sumário",
    tableOfContentsAriaLabel: "Sumário da documentação",
    sectionsAriaLabel: "Seções da documentação",
    breadcrumbAriaLabel: "Navegação estrutural",
    breadcrumbRoot: "Documentação",
    startHere: "Comece aqui",
    notFoundBreadcrumb: "Não encontrada",
    notFoundTitle: "Não encontramos essa seção",
    notFoundBody:
      "A URL aponta para uma seção que não está no sumário. Volte ao início da documentação e escolha uma seção da lista.",
    fallbackTitle: "A fonte em inglês está sendo exibida",
    fallbackBody:
      "Esta seção ainda não foi traduzida para o idioma selecionado. Exibimos a fonte em inglês sem alterar comandos, identificadores, rotas nem exemplos de código.",
    copyCode: "Copiar código",
    copiedCode: "Copiado",
    copiedToast: "Copiado para a área de transferência",
    screenshotPlaceholder: "[CAPTURA DE TELA]",
  },
  landing: {
    eyebrow: "Documentação",
    title: "Conheça a plataforma, configure-a para sua equipe e acompanhe o trabalho dos runners.",
    description:
      "Um guia do Backplane pensado para operadores, desde a compreensão dos runners até a configuração de funções personalizadas. Ele explica diretamente o que funciona e o que ainda precisa evoluir.",
    featuredLabel: "Comece aqui",
    featuredDescription:
      "Uma explicação breve sobre o que a plataforma faz, para quem ela foi criada e onde continuar.",
  },
  mcpReference: {
    navAriaLabel: "Referência MCP",
    searchAriaLabel: "Pesquisar na referência MCP",
    searchPlaceholder: 'Pesquisar ferramentas…  ("/" para focar)',
    filterAriaLabel: "Filtrar por tipo",
    filterLabels: {
      all: "Todos",
      read: "Leitura",
      write: "Escrita",
      composite: "Composto",
    },
    noMatches: "Nenhum resultado.",
    noMatchesFor: 'Nenhum resultado para "{{query}}".',
    clearSearchAndFilters: "Limpar pesquisa e filtros",
    promptsGroup: "Prompts",
    resourcesGroup: "Recursos MCP",
    noResultsDetail:
      "Nada corresponde à pesquisa e aos filtros atuais. Limpe-os no painel da lista para recomeçar.",
    selectDetailBeforeShortcut:
      "Selecione uma ferramenta da lista para ver seus parâmetros, alertas e um prompt de exemplo, ou pressione",
    selectDetailAfterShortcut: "para pesquisar.",
    copyToolId: "Copiar identificador da ferramenta",
    parameters: "Parâmetros",
    gotchas: "Alertas",
    dangerZone: "Zona de perigo",
    examplePrompt: "Prompt de exemplo",
    relatedTools: "Ferramentas relacionadas",
    backToList: "Voltar à lista",
    noParameters: "Sem parâmetros.",
    parameterName: "Nome",
    parameterRequired: "Obrigatório",
    parameterDescription: "Descrição",
    requiredValue: "obrigatório",
    optionalValue: "opcional",
    copyExamplePrompt: "Copiar prompt de exemplo",
    annotationReadOnly: "Somente leitura",
    annotationDestructive: "Destrutiva",
    annotationIdempotent: "Idempotente",
    wireDescriptionTitle: "O que o modelo vê",
    inDefaultHand: "Na mão padrão",
  },
  groupTitles: {
    introduction: "Introdução",
    "core-concepts": "Conceitos principais",
    installing: "Instalação do Backplane",
    "getting-started": "Primeiros passos",
    configuration: "Configuração",
    operating: "Operação da plataforma",
    "under-the-hood": "Por dentro da plataforma",
    extending: "Extensão do Backplane",
    reference: "Referência",
    "honest-remarks": "Observações transparentes",
  },
  sectionTitles: {
    "what-backplane-is": "O que é o Backplane",
    "what-it-is-not": "O que ele NÃO é",
    "quick-tour": "Visão geral rápida (5 minutos)",
    "workspaces-boards-columns-cards": "Espaços de trabalho, quadros, colunas e cartões",
    runners: "Runners (o processo com credenciais)",
    "agent-teams": "Equipes de agentes",
    "roles-and-pipelines": "Funções e pipelines",
    prompts: "Prompts",
    approvals: "Aprovações",
    "loop-mode": "Modo de loop",
    skills: "Habilidades (conhecimento procedural versionado)",
    "install-with-docker-compose": "Instalação com Docker Compose",
    "securing-a-self-hosted-deployment": "Proteção de uma implantação auto-hospedada",
    "upgrading-backplane": "Atualização do Backplane",
    "backup-and-restore": "Backup e restauração",
    "creating-your-first-workspace": "Criação do seu primeiro espaço de trabalho",
    "your-first-board-and-card": "Seu primeiro quadro e seu primeiro cartão",
    "installing-the-mcp-server": "Instalação do servidor MCP no seu cliente de agentes",
    "registering-a-runner": "Registro de um Runner",
    "your-first-pipeline-run": "Sua primeira execução do pipeline (guia passo a passo)",
    "troubleshooting-your-first-run": "Solução de problemas da primeira execução",
    "pipeline-builder": "Construtor de pipelines: todos os campos explicados",
    "prompt-authoring-guide": "Guia de criação de prompts",
    "custom-roles": "Funções personalizadas (o benefício real)",
    sensors: "Sensores",
    "approval-categories-and-risk-scoring": "Categorias de aprovação e pontuação de risco",
    "budget-and-cost-controls": "Controles de orçamento e custos",
    "git-configuration-and-review-modes": "Configuração do Git e modos de revisão",
    "reading-the-runner-overview": "Leitura da visão geral dos Runners",
    "debugging-a-stuck-card": "Diagnóstico de um cartão bloqueado",
    "the-observer-panel": "O painel do observador",
    "activity-history-and-audit-logs": "Histórico de atividades e logs de auditoria",
    "webhooks-and-external-notifications": "Webhooks e notificações externas",
    "rollback-and-recovery-playbook": "Guia de reversão e recuperação",
    "architecture-overview": "Visão geral da arquitetura (as quatro superfícies)",
    "event-bus-and-websocket-model": "O barramento de eventos e o modelo WebSocket",
    "fractional-indexing": "Indexação fracionária",
    idempotency: "Idempotência e sua importância",
    "platform-authority-principle": "Princípio de autoridade da plataforma",
    "model-agnostic-roles": "Funções independentes do modelo (visão futura)",
    "adding-a-new-mcp-tool": "Como adicionar uma nova ferramenta MCP",
    "adding-a-new-pipeline-stage-variant": "Como adicionar uma variante de etapa do pipeline",
    "integrating-a-new-git-host": "Integração de um novo provedor Git",
    "writing-a-custom-sensor": "Como criar um sensor personalizado",
    "mcp-tool-catalog": "Catálogo de ferramentas MCP",
    "mcp-toolsets": "Toolsets MCP",
    "mcp-prompt-catalog": "Catálogo de prompts MCP",
    "event-taxonomy": "Taxonomia de eventos",
    "column-type-semantics": "Semântica dos tipos de coluna",
    "card-type-and-priority": "Tipo e prioridade dos cartões",
    "api-authentication-modes": "Modos de autenticação da API",
    "environment-variables": "Variáveis de ambiente",
    "what-works-well": "O que funciona bem",
    "known-rough-edges": "Limitações conhecidas",
    "actively-working-on": "No que estamos trabalhando ativamente",
    "the-north-star": "A estrela-guia",
  },
};
